#include "unity/unity_fixture.h"

// declare all your group runners:
extern TEST_GROUP_RUNNER(ARGV);
extern TEST_GROUP_RUNNER(CONFIGS);
extern TEST_GROUP_RUNNER(SYSINFO);
extern TEST_GROUP_RUNNER(HASHTABLE);
extern TEST_GROUP_RUNNER(HASHSET);
extern TEST_GROUP_RUNNER(RINGBUF);
extern TEST_GROUP_RUNNER(BATCHER);
extern TEST_GROUP_RUNNER(ZEROCOPY);
extern TEST_GROUP_RUNNER(PERF);
extern TEST_GROUP_RUNNER(DB_LMDB);
extern TEST_GROUP_RUNNER(FRAMING);
extern TEST_GROUP_RUNNER(PROTOCOL);
extern TEST_GROUP_RUNNER(SOCKET);
extern TEST_GROUP_RUNNER(NET);
extern TEST_GROUP_RUNNER(APP);
extern TEST_GROUP_RUNNER(LOGGER);
extern TEST_GROUP_RUNNER(FILES);
extern TEST_GROUP_RUNNER(RANDOM);
extern TEST_GROUP_RUNNER(PRIME);
extern TEST_GROUP_RUNNER(LOGSTORE);

extern TEST_GROUP_RUNNER(BACKTRACE);

static void RunAllTests(void) {
    RUN_TEST_GROUP(ARGV);
    RUN_TEST_GROUP(CONFIGS);
    RUN_TEST_GROUP(SYSINFO);
    RUN_TEST_GROUP(HASHTABLE);
    RUN_TEST_GROUP(HASHSET);
    RUN_TEST_GROUP(RINGBUF);
    RUN_TEST_GROUP(BATCHER);
    RUN_TEST_GROUP(ZEROCOPY);
    RUN_TEST_GROUP(PERF);
    RUN_TEST_GROUP(DB_LMDB);
    RUN_TEST_GROUP(FRAMING);
    RUN_TEST_GROUP(PROTOCOL);
    RUN_TEST_GROUP(SOCKET);
    RUN_TEST_GROUP(NET);
    RUN_TEST_GROUP(APP);
    RUN_TEST_GROUP(LOGGER);
    RUN_TEST_GROUP(FILES);
    RUN_TEST_GROUP(RANDOM);
    RUN_TEST_GROUP(PRIME);
    RUN_TEST_GROUP(LOGSTORE);
    RUN_TEST_GROUP(BACKTRACE);
}

int main(int argc, const char *argv[]) {
    return UnityMain(argc, argv, RunAllTests);
}
